# Exercise 1

1.  Write a Python program to load the iris data from a given csv file into a dataframe and print the shape of the data, type of the data and first 3 rows.

In [1]:
import numpy as np 
import pandas as pd
df = pd.read_csv("Iris.csv")

print("\n")
print("Shape : ")
print(df.shape)
print("\n")
print("Datatype : ")
print(df.dtypes)
print("\n")
print("First 3 rows : ")
df.head(3)



Shape : 
(150, 6)


Datatype : 
Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object


First 3 rows : 


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa

2. Write a Python program using Scikit-learn to print the keys, number of rows-columns, feature names and the description of the Iris data

In [2]:
print("Keys : ")
print(df.keys())
print("\n")
print("size : ")
print(df.size)
print("\n")
print("Row size : ")
print(df.shape[0])
print("\n")
print("Col size : ")
print(df.shape[1])
print("\n")

Keys : 
Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')


size : 
900


Row size : 
150


Col size : 
6




3.  Write a Python program to get the number of observations, missing values and nan values

In [3]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
None


In [20]:
from sklearn.preprocessing import OneHotEncoder

# Instantiate the OneHotEncoder
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore',drop='first')

# Identify categorical columns (object dtype)
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
print(categorical_cols)

# Apply OneHotEncoder to the categorical columns and create a DataFrame from the result
encoded = pd.DataFrame(encoder.fit_transform(df[categorical_cols]),
                       columns=encoder.get_feature_names_out(categorical_cols),
                       index=df.index)
print(encoder.get_feature_names_out(categorical_cols))

# Drop the original categorical columns and join the encoded dataframe
df_encoded = df.drop(columns=categorical_cols).join(encoded)
df_encoded.head()

['Species']
['Species_Iris-versicolor' 'Species_Iris-virginica']


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0   1            5.1           3.5            1.4           0.2   
1   2            4.9           3.0            1.4           0.2   
2   3            4.7           3.2            1.3           0.2   
3   4            4.6           3.1            1.5           0.2   
4   5            5.0           3.6            1.4           0.2   

   Species_Iris-versicolor  Species_Iris-virginica  
0                      0.0                     0.0  
1                      0.0                     0.0  
2                      0.0                     0.0  
3                      0.0                     0.0  
4                      0.0                     0.0

In [1]:
from sklearn.impute import SimpleImputer
import numpy as np
import pandas as pd

# Create a sample DataFrame with missing values
data = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, 5]
})

print("Original DataFrame:")
print(data)

# Instantiate SimpleImputer with strategy 'mean' to replace missing values by the column mean
imputer = SimpleImputer(strategy='mean')

# Fit the imputer on the data and transform it
data_imputed = pd.DataFrame(imputer.fit_transform(data), columns=data.columns)

print("\nDataFrame after imputing missing values with mean:")
print(data_imputed)

Original DataFrame:
     A    B
0  1.0  NaN
1  2.0  2.0
2  NaN  3.0
3  4.0  4.0
4  5.0  5.0

DataFrame after imputing missing values with mean:
     A    B
0  1.0  3.5
1  2.0  2.0
2  3.0  3.0
3  4.0  4.0
4  5.0  5.0


In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# Sample categorical data as a 2D array (each row is an observation)
data = np.array([
    ['red'],
    ['green'],
    ['blue'],
    ['green']
])

# Create the OneHotEncoder instance
encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder and transform the data
data_encoded = encoder.fit_transform(data)
print("data encoded ")
print(data_encoded)

# Retrieve feature names for each one-hot encoded column
# Here, 'color' is the name we assign to the original column
column_names = encoder.get_feature_names_out(['color'])

# Create a DataFrame with each one-hot vector as an individual column
df_encoded = pd.DataFrame(data_encoded, columns=column_names)

print("Original Data:\n", data)
print("\nOne-Hot Encoded DataFrame:\n", df_encoded)


data encoded 
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
Original Data:
 [['red']
 ['green']
 ['blue']
 ['green']]

One-Hot Encoded DataFrame:
    color_blue  color_green  color_red
0         0.0          0.0        1.0
1         0.0          1.0        0.0
2         1.0          0.0        0.0
3         0.0          1.0        0.0


In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# Sample DataFrame with multiple categorical columns
data = pd.DataFrame({
    'Color': ['Red', 'Green', 'Red', 'Green'],
    'Size': ['S', 'M', 'S', 'M'],
    'Shape': ['Circle', 'Square', 'Circle', 'Square']
})

# Initialize the OneHotEncoder
encoder = OneHotEncoder(sparse_output=False , drop= "if_binary")

# Fit and transform the categorical columns
data_encoded = encoder.fit_transform(data)

# Retrieve the feature names for the encoded columns
column_names = encoder.get_feature_names_out(data.columns)
print(column_names)
# Create a new DataFrame with one-hot encoded columns
encoded_df = pd.DataFrame(data_encoded, columns=column_names)

# Display the results
print("Original DataFrame:\n", data)
print("\nOne-Hot Encoded DataFrame:\n", encoded_df)


['Color_Red' 'Size_S' 'Shape_Square']
Original DataFrame:
    Color Size   Shape
0    Red    S  Circle
1  Green    M  Square
2    Red    S  Circle
3  Green    M  Square

One-Hot Encoded DataFrame:
    Color_Red  Size_S  Shape_Square
0        1.0     1.0           0.0
1        0.0     0.0           1.0
2        1.0     1.0           0.0
3        0.0     0.0           1.0


In [ ]:
def  cse()